### ISSUE TITLE
VoiceMeeter Advanced Toogle - Unable to choose images

### ISSUE THREAD

**Issue by Inzaniity** [BarRaider/streamdeck-voicemeeter#3]
When I use the VoiceMeeter Advanced Toogle option and want to select images for Mode1 and Mode2, the filter is set to "all supported formats" but no images are shwon in the filebrowser. 

When I select the same folder for action images it works just fine. (png files) 

![image](https://user-images.githubusercontent.com/17164019/51245955-76736a00-1989-11e9-996e-1c15c3b80b58.png)

**Comment by themdrnsamurai** [comment]
This. I have the same issue. If I try and load an image I get a value like "C:\fakepath\C%3A%2Ftools%2FStreamdeck%2Fsd_blue.png" in the image path and obviously no image itself.

**Comment by themdrnsamurai** [comment]
Note: I just ran voicemeeter and the images showed up (it hadn't been running). You might not want that as a dependancy path.

**Comment by Inzaniity** [comment]
> Note: I just ran voicemeeter and the images showed up (it hadn't been running). You might not want that as a dependancy path.

Can't confirm that, had Voicemeeter running when I tried it.

**Comment by JoergAp** [comment]
Part of the problem seems to be the windows localisation. At least in german you are not automatically shown the image files that are recognized. Only if you put an "*" in the path you will be shown all files in the directory. If you switch to english its working.

The next problem is, that these changes are not saved in the profile and will crash all new buttons you have edited up to this point.

![image](https://user-images.githubusercontent.com/46818081/51391276-ee7c9400-1b31-11e9-8ffa-e797961e49a4.png)
![image](https://user-images.githubusercontent.com/46818081/51391316-05bb8180-1b32-11e9-83f8-c7bca5b53bcd.png)
![image](https://user-images.githubusercontent.com/46818081/51391322-0a803580-1b32-11e9-88a8-a0561327c8af.png)

**Comment by hringriin** [comment]
I have an English Version of Win 10 64Bit Educational installed. I guess it is not the system's language, either. Entering the `*` as the filename and *open* it seems to work, though. Thanks! :-)

**Comment by BarRaider** [comment]
Hi,

Sorry for the late reply.
This issue was identified as a bug in the Stream Deck App 4.0 version.
It has been resolved in version 4.1, please upgrade to the latest Stream Deck version.
