### ISSUE TITLE
Button on/off

### ISSUE THREAD

**Issue by xgamerg1rl** [BarRaider/streamdeck-voicemeeter#6]
well hello there,

found your Plugin for the Elgato and it's great.
but: Is it possible to set a button for *press* Channel 1 A1 active - *press* Channel 1 A1 inactive ?
so by pressing the same button, it will active if inactive and inactivate if active ;)

or: is it possible to link the macro-button feature to a button in the Streamdeck ? :)

greetings from germany,
michelle

**Comment by Inzaniity** [comment]
What you are searching for is the "VoiceMeeter Advanced Toggle" 

In there set Mode1 Key Presso to e.g. `Strip[4].A1 = 1;`
Mode 1 Check is for detecting which state the `Strip[4].A1` has and therefore sets the icon accordingly and you don't have to press twice if you want it to be disabled or so.

set Mode 2 Key Press to `Strip[4].A1 =0;`

When chosing images put a `*` in the field that says "Filename", else it won't show any images.

Title Value will display the value of given parameter on the Streamdeck, I have it empty because images are enough for me.

**Comment by xgamerg1rl** [comment]
Perfect. I'll try it when I get home :)

**Comment by xgamerg1rl** [comment]
> 
> 
> What you are searching for is the "VoiceMeeter Advanced Toggle"
> 
> In there set Mode1 Key Presso to e.g. `Strip[4].A1 = 1;`
> Mode 1 Check is for detecting which state the `Strip[4].A1` has and therefore sets the icon accordingly and you don't have to press twice if you want it to be disabled or so.
> 
> set Mode 2 Key Press to `Strip[4].A1 =0;`
> 
> When chosing images put a `*` in the field that says "Filename", else it won't show any images.
> 
> Title Value will display the value of given parameter on the Streamdeck, I have it empty because images are enough for me.

hmm... it's not working... Everytime I add the button to the deck, it shows this little exclamation mark and after that, the Buttons settings are empty again... :(

**Comment by xgamerg1rl** [comment]
@Inzaniity :) Sry aboud disturbing you... but I needed to fixed this little problem... :/

**Comment by Inzaniity** [comment]
> @Inzaniity :) Sry aboud disturbing you... but I needed to fixed this little problem... :/

I really don't know whats the issue then. Maybe you can contact me on Discord and send me some screenshots? 

Discord: Inzaniity#3591

**Comment by BarRaider** [comment]
Hi,

Sorry for the late reply.
If you are still having issues, I have a dedicated help channel on my Discord server.
Link can be found at https://barraider.github.io/
